# Generated by Django 4.1 on 2023-05-29 22:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='salary_ammount',
            new_name='salary_amount',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='exire_date',
            new_name='expire_date',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medical_type',
            new_name='medical_typ',
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='prescription',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companybank',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeebank',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeebank',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalStoreApp.employee'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
